### ISSUE TITLE
CLI can't find templates

### ISSUE THREAD

**Issue by kevoneil** [bigtestjs/cli#18]
Installed `v0.1.1` and getting the following error:

```
[BigTest]: ERROR: Initialize failed :(
[BigTest]: ERROR: ENOENT: no such file or directory, stat '/Users/kevinoneil/Projects/bigtest-example/node_modules/@bigtest/cli/templates/bigtest'
```

I think we will need to add the `templates` directory into the `files` [field](https://github.com/bigtestjs/cli/blob/master/package.json#L7).

Can I open a PR to fix this?

**Comment by Robdel12** [comment]
Oops. Absolutely I’d merge right away!
